apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: library-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: library-api
    spec:
      containers:
        - name: library-api
          image: 'gcr.io/spring-boot-241015/library-api:v1'
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: library-api-service
  labels:
    name: library-api-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: library-api
  type: LoadBalancer
